#LDFLAGS for loader flags; EXTRA_CFLAGS for file inclusion
#LDADD for linking and loading the library
SRCS=binary-search.cpp  main.cpp merge-sort.cpp quick-sort.cpp
PROG=alogs
CFLAGS=-g -Wall -I.
CC= g++
include /usr/lib/build/linux.prog.mk
