#LDFLAGS for loader flags; EXTRA_CFLAGS for file inclusion
#LDADD for linking and loading the library
SRCS=./String.c  smallestLargestWordFromString.c
PROG=strings
CFLAGS=-g -Wall -I.
include /usr/lib/build/linux.prog.mk
