#LDFLAGS for loader flags; EXTRA_CFLAGS for file inclusion
#LDADD for linking and loading the library
SRCS=./mid_of_linkedlist.cpp 
PROG=mid_of_linkedlist
CFLAGS=-g -Wall
CC= g++
include /usr/lib/build/linux.prog.mk
