#LDFLAGS for loader flags; EXTRA_CFLAGS for file inclusion
#LDADD for linking and loading the library
SRCS=./cpp-version.cpp 
PROG=cpp-version
CFLAGS=-g -Wall
CC= g++
include /usr/lib/build/linux.prog.mk
