#LDFLAGS for loader flags; EXTRA_CFLAGS for file inclusion
#LDADD for linking and loading the library
SRCS=./2stacks.cpp 
PROG=2stacks-1array
CFLAGS=-g -Wall
CC= g++
include /usr/lib/build/linux.prog.mk
