#LDFLAGS for loader flags; EXTRA_CFLAGS for file inclusion
#LDADD for linking and loading the library
SRCS=./signaling.c 
PROG=signaling
CFLAGS=-g -Wall
LDFLAGS=-lpthread
include /usr/lib/build/linux.prog.mk
