#LDFLAGS for loader flags; EXTRA_CFLAGS for file inclusion
#LDADD for linking and loading the library
SRCS=./array.c ./rotate_array.c 
PROG=array
CFLAGS=-g -Wall -I./
include /usr/lib/build/linux.prog.mk
