#LDFLAGS for loader flags; EXTRA_CFLAGS for file inclusion
#LDADD for linking and loading the library
SRCS=./producer_consumer.c ./queue.c 
PROG=producer_consumer
CFLAGS=-g -Wall -I/usr/include/glib-2.0
LDFLAGS=-lpthread
include /usr/lib/build/linux.prog.mk
