#LDFLAGS for loader flags; EXTRA_CFLAGS for file inclusion
#LDADD for linking and loading the library
SRCS=./producer_consumer.c 
PROG=producer_consumer
CFLAGS=-g -Wall
LDFLAGS=-pthread
include /usr/lib/build/linux.prog.mk
