#LDFLAGS for loader flags; EXTRA_CFLAGS for file inclusion
#LDADD for linking and loading the library
SRCS=./linkedlist.cpp 
PROG=linkedlist
CFLAGS=-g -Wall
CC= g++
include /usr/lib/build/linux.prog.mk
