#LDFLAGS for loader flags; EXTRA_CFLAGS for file inclusion
#LDADD for linking and loading the library
SRCS=./stack.cpp  queue.cpp main.cpp
PROG=stack
CFLAGS=-g -Wall -I./
CC= g++
include /usr/lib/build/linux.prog.mk
