#LDFLAGS for loader flags; EXTRA_CFLAGS for file inclusion
#LDADD for linking and loading the library
SRCS=./Rendezvous.c 
PROG=Rendezvous
CFLAGS=-g -Wall
LDFLAGS=-lpthread
include /usr/lib/build/linux.prog.mk
