#LDFLAGS for loader flags; EXTRA_CFLAGS for file inclusion
#LDADD for linking and loading the library
SRCS=./main.cpp 
PROG=enum
CFLAGS=-g -Wall -std=c++17
CC= g++
include /usr/lib/build/linux.prog.mk
