KMOD=mymodule
EXTRA_CFLAGS = -I $(PWD)/header
SRCS=main.c def.c
VPATH:=$(PWD)/../complex-kernel-module/main $(PWD)/def
include /home/msys/qnap/working/zpool-porting/qnap/build/linux.common.mk
include /home/msys/qnap/working/zpool-porting/qnap/build/linux.kmod.mk
